{
 "title": "Azure EntraID Apps Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application Registrations / SPs",
   "type": "stat",
   "description": "Total Number of Azure EntraID Application Registration or Service Principals Checked",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (application_id) (azad_secret_expiry_timestamp))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expired Secrets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(azad_secret_expiry_timestamp{status=\"EXPIRED\"})"
    }
   ]
  },
  {
   "title": "Expired or Expiring in 30 days",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "azad_secret_expiry_timestamp-time()"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Azure AD App Registrations Status",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "azad_secret_expiry_timestamp" }
   ]
  }
 ]
}